travis: fix build failure due to old version of coverage
Error on travisci when running 'coverage' testenv...

Traceback (most recent call last):
  File ".tox/coverage/bin/coveralls", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/travis/build/Etherios/python-devicecloud/.tox/coverage/lib/python2.7/site-packages/pkg_resources.py", line 2829, in <module>
    working_set = WorkingSet._build_master()
  File "/home/travis/build/Etherios/python-devicecloud/.tox/coverage/lib/python2.7/site-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/travis/build/Etherios/python-devicecloud/.tox/coverage/lib/python2.7/site-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/travis/build/Etherios/python-devicecloud/.tox/coverage/lib/python2.7/site-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: coverage>=3.6,<3.999
ERROR: InvocationError: '/home/travis/build/Etherios/python-devicecloud/.tox/coverage/bin/coveralls'